#
# Makefile
#
# Computer Science 50
# Problem Set 4
#

recover: recover.c Makefile
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o recover recover.c -lcs -lm

clean:
	rm -f *.o core recover
