#
# Makefile
#
# Computer Science 50
# Problem Set 4
#

resize: resize.c Makefile
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -Wno-unused-variable -o resize resize.c -lcs -lm

clean:
	rm -f *.o core resize
